### PR TITLE
Wrap isFeatureSupported on RxBilling

### PR DESCRIPTION
**Pull request by mrstif**
- Adds support for [isFeatureSupported](https://developer.android.com/reference/com/android/billingclient/api/BillingClient#isfeaturesupported) method from `BillingClient` in `RxBilling`

### CODE REVIEW

**Comment by KChernenko** [comment]
Hi, thanks for the PR! Everything is looking good for me, but you've pointed the PR to the `master` branch, which wasn’t updated for a while. Before merging, could I ask you to fetch latest changes from it?

**Comment by mrstif** [comment]
@KChernenko the outdated branch seems to be `develop` and not `master` 
do you prefer that I create a new branch starting from `develop` with only my commits?

**Comment by KChernenko** [comment]
@mrstif yep, it would be great!

**Comment by mrstif** [comment]
Thanks, @KChernenko

**Pull request merged**
